@startuml
title __T2: Token Modification/Forgery__
actor Bob
participant GroupServer

Bob <--> GroupServer: Share K<sub>GB</sub>
Bob -> GroupServer: Bob || {Request Token || GroupList[]}K<sub>GB</sub>
GroupServer -> Bob: {pToken || [H(pToken)]k<sub>G</sub><sup>-1</sup>}K<sub>GB</sub>

@enduml