@startuml
title __T3: Unauthorized File Servers__
actor Bob
participant FS
participant Trent
participant GroupServer

Bob <--> GroupServer: Share session secret K<sub>GB</sub>
GroupServer <--> Trent: Share strong symmetric secret K<sub>TG</sub>
Bob -> Trent: Bob || {[pToken]k<sub>G</sub><sup>-1</sup> || FileServer_X || C<sub>1</sub>}K<sub>GB</sub>
note left: Challenge C<sub>1</sub> sent to verify Trent

Trent -> GroupServer: Requesting session key
GroupServer -> Trent: C<sub>2</sub>
Trent -> GroupServer: {C<sub>2</sub> || Bob}K<sub>TG</sub>
GroupServer -> Trent: {Bob || K<sub>GB</sub>}K<sub>TG</sub>
Trent -> Bob: {k<sub>FSX</sub> || k<sub>B</sub><sup>-1</sup> || C<sub>1</sub>}K<sub>GB</sub>

create FS
Bob -> FS: Bob || [FileServer_X || g<sup>b</sup> mod q]k<sub>B</sub><sup>-1</sup>
note left: Choose random b
FS -> Trent: Bob
note right: FS requests Bob's public key
Trent -> FS: k<sub>B</sub>

FS -> FS: Verify Bob through k<sub>B</sub>
FS -> Bob: FS<sub>X</sub> || [Bob || g<sup>f</sup> mod q]k<sub>FSX</sub><sup>-1</sup>
Bob -> Bob: Verify FileServer_X through k<sub>FSX</sub>

Bob <--> FS: Share K<sub>BF</sub>
@enduml