#!/bin/bash
jar_name=bcprov-jdk15on-158.jar

echo "Starting ClientApp..."
if [[ $PWD != *"$thePath/src"* ]]; then
  cd ./src
fi
pwd
echo "Sleeping..."
if [[ $testing =~ "True" ]]; then
  $clientCmd < $clientIn
elif [ -z "$testing" ]; then
  $clientCmd
fi
