#!/bin/bash
jar_name=bcprov-jdk15on-158.jar
thePath="cs1653-2017fa-jbd29-mar257-zds14"


echo "Starting ClientApp..."
if [[ $PWD != *"$thePath"* ]]; then
  cd ./src/
fi
pwd
echo "Sleeping..."
if [[ $testing =~ "True" ]]; then
  $clientCmd < $clientIn
elif [ -z "$testing" ]; then
  $clientCmd
fi
