#!/bin/bash
jar_name=bcprov-jdk15on-158.jar
clientCmd="java -cp .:$jar_name RunClientApp"
clientIn="../ClientInput"

echo "Starting ClientApp..."
cd /Users/maxreno/school/cs1653/cs1653-2017fa-jbd29-mar257-zds14/src
pwd

echo "Auto test? (y/n)"
read tt

if test "$tt" == "y"
then
  $clientCmd = "$clientCmd < $clientIn"
fi

echo "Sleeping..."
$clientCmd
