#!/bin/bash
jar_name=bcprov-jdk15on-158.jar
clientCmd="java -cp .:$jar_name RunClientApp"
clientIn="../ClientInput"

echo "Starting ClientApp..."
cd /Users/maxreno/school/cs1653/cs1653-2017fa-jbd29-mar257-zds14/src
pwd

echo "Auto test? (1/0)"
read tt
echo "Sleeping..."

if test "$tt" == "1"
then
  $clientCmd < $clientIn
else
  $clientCmd
fi
