#!/bin/env bash
jar_name=bcprov-jdk15on-158.jar

echo "Starting GroupServer..."
if [[ $PWD != *"$thePath"* ]]; then
  cd ./src/
fi
GSin="../GSinput"
pwd
echo "Sleeping..."
java -cp .:$jar_name RunGroupServer < $GSin
