#!/bin/bash
jar_name=bcprov-jdk15on-158.jar

echo "Starting GroupServer..."
cd /Users/maxreno/school/cs1653/cs1653-2017fa-jbd29-mar257-zds14/src
pwd

GSin="../GSinput"

echo "Sleeping..."
java -cp .:$jar_name RunGroupServer < $GSin
